SELECT [AssessmentIdentifier]
      ,[Namespace]
      ,[AssessmentTitle]
      ,[AssessmentCategoryDescriptorId]
      ,[AssessmentForm]
      ,[AssessmentVersion]
      ,[RevisionDate]
      ,[MaxRawScore]
      ,[Nomenclature]
      ,[AssessmentFamily]
      ,[EducationOrganizationId]
      ,[AdaptiveAssessment]
      ,[Discriminator]
      ,[CreateDate]
      ,[LastModifiedDate]
      ,CAST([Id] AS varchar(36)) AS [Id]
  FROM [edfi].[Assessment]
  WHERE [Namespace] = 'uri://illuminateed.com';

