SELECT [CourseCode]
      ,[EducationOrganizationId]
      ,[CourseTitle]
      ,[NumberOfParts]
      ,[AcademicSubjectDescriptorId]
      ,[CourseDescription]
      ,[TimeRequiredForCompletion]
      ,[DateCourseAdopted]
      ,[HighSchoolCourseRequirement]
      ,[CourseGPAApplicabilityDescriptorId]
      ,[CourseDefinedByDescriptorId]
      ,[MinimumAvailableCredits]
      ,[MinimumAvailableCreditTypeDescriptorId]
      ,[MinimumAvailableCreditConversion]
      ,[MaximumAvailableCredits]
      ,[MaximumAvailableCreditTypeDescriptorId]
      ,[MaximumAvailableCreditConversion]
      ,[CareerPathwayDescriptorId]
      ,[MaxCompletionsForCredit]
      ,[Discriminator]
      ,[CreateDate]
      ,[LastModifiedDate]
      ,CAST([Id] AS varchar(36)) AS [Id]
  FROM [edfi].[Course];
