SELECT [AddressTypeDescriptorId]
      ,[City]
      ,[EducationOrganizationId]
      ,[PostalCode]
      ,[StateAbbreviationDescriptorId]
      ,[StreetNumberName]
      ,[ApartmentRoomSuiteNumber]
      ,[BuildingSiteNumber]
      ,[NameOfCounty]
      ,[CountyFIPSCode]
      ,[Latitude]
      ,[Longitude]
      ,[DoNotPublishIndicator]
      ,[CongressionalDistrict]
      ,[LocaleDescriptorId]
      ,[CreateDate]
  FROM [edfi].[EducationOrganizationAddress]


