SELECT [LocalCourseCode]
      ,[SchoolId]
      ,[SchoolYear]
      ,[SectionIdentifier]
      ,[SessionName]
      ,[SequenceOfCourse]
      ,[EducationalEnvironmentDescriptorId]
      ,[MediumOfInstructionDescriptorId]
      ,[PopulationServedDescriptorId]
      ,[AvailableCredits]
      ,[AvailableCreditTypeDescriptorId]
      ,[AvailableCreditConversion]
      ,[InstructionLanguageDescriptorId]
      ,[LocationSchoolId]
      ,[LocationClassroomIdentificationCode]
      ,[OfficialAttendancePeriod]
      ,[Discriminator]
      ,[CreateDate]
      ,[LastModifiedDate]
      ,CAST([Id] AS varchar(36)) AS [Id]
  FROM [edfi].[Section];

