SELECT [EntryDate]
      ,[SchoolId]
      ,[StudentUSI]
      ,[PrimarySchool]
      ,[EntryGradeLevelDescriptorId]
      ,[EntryGradeLevelReasonDescriptorId]
      ,[EntryTypeDescriptorId]
      ,[RepeatGradeIndicator]
      ,[ClassOfSchoolYear]
      ,[SchoolChoiceTransfer]
      ,[ExitWithdrawDate]
      ,[ExitWithdrawTypeDescriptorId]
      ,[ResidencyStatusDescriptorId]
      ,[GraduationPlanTypeDescriptorId]
      ,[EducationOrganizationId]
      ,[GraduationSchoolYear]
      ,[EmployedWhileEnrolled]
      ,[CalendarCode]
      ,[SchoolYear]
      ,[FullTimeEquivalency]
      ,[TermCompletionIndicator]
      ,[Discriminator]
      ,[CreateDate]
      ,[LastModifiedDate]
      ,CAST([Id] AS varchar(36)) AS [Id]
  FROM [edfi].[StudentSchoolAssociation]

