SELECT [StudentUSI]
      ,[PersonalTitlePrefix]
      ,[FirstName]
      ,[MiddleName]
      ,[LastSurname]
      ,[GenerationCodeSuffix]
      ,[MaidenName]
      ,[BirthDate]
      ,[BirthCity]
      ,[BirthStateAbbreviationDescriptorId]
      ,[BirthInternationalProvince]
      ,[BirthCountryDescriptorId]
      ,[DateEnteredUS]
      ,[MultipleBirthStatus]
      ,[BirthSexDescriptorId]
      ,[CitizenshipStatusDescriptorId]
      ,[StudentUniqueId]
      ,[Discriminator]
      ,[CreateDate]
      ,[LastModifiedDate]
      ,CAST([Id] AS varchar(36)) AS [Id]
  FROM [edfi].[Student]


