INSERT INTO [edfi].[Course]
           ([CourseCode]
           ,[EducationOrganizationId]
           ,[CourseTitle]
           ,[NumberOfParts]
           ,[AcademicSubjectDescriptorId]
           ,[CourseDescription]
           ,[TimeRequiredForCompletion]
           ,[DateCourseAdopted]
           ,[HighSchoolCourseRequirement]
           ,[CourseGPAApplicabilityDescriptorId]
           ,[CourseDefinedByDescriptorId]
           ,[MinimumAvailableCredits]
           ,[MinimumAvailableCreditTypeDescriptorId]
           ,[MinimumAvailableCreditConversion]
           ,[MaximumAvailableCredits]
           ,[MaximumAvailableCreditTypeDescriptorId]
           ,[MaximumAvailableCreditConversion]
           ,[CareerPathwayDescriptorId]
           ,[MaxCompletionsForCredit]
           ,[Discriminator]
           ,[CreateDate]
           ,[LastModifiedDate]
           ,[Id])
VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s) 
ON CONFLICT DO NOTHING;