INSERT INTO [edfi].[StudentSchoolAssociation]
           ([EntryDate]
           ,[SchoolId]
           ,[StudentUSI]
           ,[PrimarySchool]
           ,[EntryGradeLevelDescriptorId]
           ,[EntryGradeLevelReasonDescriptorId]
           ,[EntryTypeDescriptorId]
           ,[RepeatGradeIndicator]
           ,[ClassOfSchoolYear]
           ,[SchoolChoiceTransfer]
           ,[ExitWithdrawDate]
           ,[ExitWithdrawTypeDescriptorId]
           ,[ResidencyStatusDescriptorId]
           ,[GraduationPlanTypeDescriptorId]
           ,[EducationOrganizationId]
           ,[GraduationSchoolYear]
           ,[EmployedWhileEnrolled]
           ,[CalendarCode]
           ,[SchoolYear]
           ,[FullTimeEquivalency]
           ,[TermCompletionIndicator]
           ,[Discriminator]
           ,[CreateDate]
           ,[LastModifiedDate]
           ,[Id])
VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
ON CONFLICT DO NOTHING;